### PR TITLE
Margin added for footer in small screens 📱

### PR DESCRIPTION
**Pull request by pseudo-usama**
As requested in issue ( #395 ) I've added some margin for footer in small screen so that footer could be easily accessible.

| Old design  | Improved design | Improved design (for pro member) |
| ------------- | ------------- | ------------- |
| image  | image | image |

### CODE REVIEW

**Review by Polydynamical — APPROVED** [review]
LGTM!

**Comment by Robogeek95** [comment]
Good one. How about adding a screenshot of your fix, this could help get this merged faster

**Comment by pseudo-usama** [comment]
> Good one. How about adding a screenshot of your fix, this could help get this merged faster

I've added screenshots in the top comment.

**Comment by raditotev** [comment]
Why is this PR still open?

**Comment by pseudo-usama** [comment]
> Why is this PR still open?

I got no idea. 🤷

**Comment by raditotev** [comment]
There are 188 open PRs at this moment, but most of them are fixing typos or removing spaces etc. This one however is different because users can't see the footer content with the ads placed above. Maybe @codediodeio is not aware of this.

**Pull request closed without merging**
