### PR TITLE
update: edit/redo of the README.md

### PR DESCRIPTION
**Pull request by TheConwayy**
### **Howdy hey 👋**

About this PR
=========

This PR is made because of the fact that I felt that there were some things that I could change about the README, so I decided to make it my first PR!

It's nothing crazy, but a start of something.

Changes made
==========

A decent amount of changes were made.</br>
Here are some:

- Added banner *(the one used in most videos)*
- Added a link to the directory *(in GitHub)* anywhere where a directory was mentioned
- Minor edits to all descriptions/text throughout all sections
- Put the "sub-projects" in alphabetical order
- Almost full re-work of the "Contributing" section
- Many other minor edits throughout the README file

*I also added myself to the contributors section, however that can be removed if you so please..*

Plans for other edits?
==============

I plan on adding a section at the bottom with any technologies used to create the website (such as things like angular, js, html, etc.). But I first have to learn how to identify these technologies. **(ADDED [0c79b86](https://github.com/fireship-io/fireship.io/pull/635/commits/0c79b862dc3fbfc3f2946401ca171b477ea3ea26))**

### CODE REVIEW

**Comment by mattruzzi** [comment]
What if we used the background he used in some of the videos?
Fireship

**Comment by TheConwayy** [comment]
> @TheConwayy What if we used the background he used in some of the videos?
> 
> Fireship
> 
> 
> 
> 

That would be a good idea, I will add that later tonight or tomorrow!

Thank you!

**Comment by mattruzzi** [comment]
Should we include the `.io`?
Fireshipio
 
Also make it link to [fireship.io](https://fireship.io/)?

**Comment by TheConwayy** [comment]
**Updated the banner to the banner that is used in most videos**

Thank you @mattruzzi for the suggestion!

**Review by Piekoszowski — APPROVED** [review]
👏 Fantastic job!

**Comment by TheConwayy** [comment]
> 👏 Fantastic job!

Thank you!!

**Comment by TheConwayy** [comment]
### Regarding last commit pushed

Changes:
======

- Centered the "header" content *(the banner, and the "designed to...")*
- Made the banner link to [fireship.io](https://fireship.io)
- Added a divider between the "header" and the rest of the content

*Thank you to @mattruzzi for the link suggestion*

**Comment by TheConwayy** [comment]
### Regarding last commit pushed [(0c79b86)](https://github.com/fireship-io/fireship.io/pull/635/commits/0c79b862dc3fbfc3f2946401ca171b477ea3ea26)

Changes:
======

- Added a "technologies" section that has some of the main technologies used throughout the website. *(please feel free to let me know what else I could add as I am not the best at identifying these yet)*

**Pull request closed without merging**
