### PR TITLE
Made github icon brighter

### PR DESCRIPTION
**Pull request by octaviookumu**
- The hexcode for the github footer logo was initially `#333`
- This meant is could not be easily seen by a user
- I changed it to `#fff` for easier visibility

### CODE REVIEW

**Comment by Ashish2097** [comment]
Can you please add a screenshot

**Comment by octaviookumu** [comment]
Sure thing. Here it is.
- Frame 1 is how it was initially
image
- Frame 2 is how it should look after the change
image

**Comment by Ashish2097** [comment]
@octaviookumu please refer to [github's logo branding](https://github.com/logos) before making changes to logos.

**Comment by Ashish2097** [comment]
@octaviookumu you can check logos for other social media apps and change them too. As I believe it is the right way of using  logos.
And can we use images instead of defining CSS for each logo.

**Comment by octaviookumu** [comment]
@Ashish2097 Thanks, I was not aware of this.
I'll make sure to follow this procedure should I make a PR concerning the logos.

**Comment by Ashish2097** [comment]
@octaviookumu yes, I think you should create an issue first and then you can start working on it. FYI @codediodeio

**Comment by octaviookumu** [comment]
@Ashish2097 No worries. I'll make sure to do that.
Thank you for the response.

**Comment by codediodeio** [comment]
Can you screenshot it with the light theme also? I'm worried it might be too light

**Comment by octaviookumu** [comment]
Oh yeah I noticed it is too light on the light theme. (didn't realize at first).
Allow me to close this PR and see if there are other issues I might be able to solve while following the right protocol.

**Pull request closed without merging**
