### PR TITLE
Add fully automated dev setup with Gitpod

### PR DESCRIPTION
**Pull request by jankeromnes**
Hello 👋 

I work on [gitpod.io](https://gitpod.io), a one-click online IDE for GitHub, and when I stumbled upon [fireship.io](https://fireship.io) your mission statement immediately resonated. 😁 🚀

In this PR, I'd like to contribute a fully automated dev setup for the Fireship repo, so that your contributors can get started running your code in one click, without having to worry about any dependencies. I've configured Gitpod to pre-install Hugo, start `npm run dev`, and automatically open a web preview.

Here is what it looks like:

[Open in Gitpod](https://gitpod.io/#https://github.com/jankeromnes/fireship.io)
Screenshot 2019-06-20 at 10 31 47
Please let me know what you think. 🙂

### CODE REVIEW

**Comment by jankeromnes** [comment]
I've rebased my Pull Request on top of the latest `master` -- still works great!

@codediodeio please take a look when you have some time. 😊

**Comment by jankeromnes** [comment]
Many thanks for the reviews!

I've just rebased on `master` again (and fixed a conflict, and bumped `node-sass` to `4.12.0` in order to support Node.js 12).

On a side note, most of the initialization steps can actually be done by Gitpod ahead-of-time, so that you can open workspaces almost instantly (instead of waiting for dependencies & builds). But to achieve this, we need to make the init steps fully non-interactive (I think right now there is a prompt from Firebase CLI about anonymous usage data collection).

Ping @codediodeio

**Comment by Robogeek95** [comment]
I tired serving the project from gitpod and i keep getting this error:

`ERROR in ./design/styles.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./design/styles.scss)`

 `Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[1]     Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (72)`

@jankeromnes, did you encounter this error and how were you able to fix it

**Comment by jankeromnes** [comment]
> I tired serving the project from gitpod and i keep getting this error:

How did you open the project in Gitpod? I.e. did you use the upstream repo URL https://github.com/fireship-io/fireship.io or did you use my fork https://github.com/jankeromnes/fireship.io ? (I ask because my fork is properly configured for Gitpod, and includes a `node-sass` upgrade to make it work with Node.js 12 -- you can try it for yourself by clicking the blue button in the PR description.)

Note that I only upgraded `node-sass` to the closest version that supports Node.js 12, but it wasn't the latest available (I think you can upgrade to two minors on top of my upgrade -- e.g. with `npm install --save node-sass` -- maybe that can solve your problem?)

**Pull request closed without merging**
